# Generated by Django 5.0.7 on 2024-07-17 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mytraveladmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(blank=True, max_length=255, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('Month', models.CharField(blank=True, max_length=200, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('bank', models.CharField(blank=True, max_length=255, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytraveladmin.packages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Confirm_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('datetime', models.DateTimeField()),
                ('person', models.IntegerField()),
                ('child', models.IntegerField()),
                ('message', models.CharField(max_length=250)),
                ('is_booked', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mytraveladmin.packages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traveluser.transaction')),
            ],
        ),
    ]
